apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pn8rqp8bi-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pn8rqp8bi-nodejs 
  name: pn8rqp8bi-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pn8rqp8bi-nodejs 
